---
#define the docker root group name
docker_group_name: 'dockerroot'

# gid to use for dockerroot group in rhel packaging
docker_group_gid: 450

# Ansible start the service?
docker_service_state: stopped

# Ansible enable it at boot?
docker_service_enabled: True

# docker configs to save into daemon.json
docker_daemon:
  group: "{{ docker_group_name }}"
  storage-driver: overlay2
  storage-opts:
    - 'overlay2.override_kernel_check=true'
  seccomp-profile: "/etc/docker/seccomp.json"
  selinux-enabled: true
  log-driver: journald
