- name: Configure text secret "{{ item.cred_desc }}"
  jenkins_script:
    script: "{{ lookup('file', 'scripts/configure_cred.groovy') }}"
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    args:
      cred_type: 'secret'
      cred_id: "{{ item.cred_id|default('') }}"
      cred_desc: "{{ item.cred_desc }}"
      cred_text: "{{ item.cred_text }}"
      cred_project: "{{ item.cred_project|default('') }}"
      cred_state: "{{ item.cred_state|default('present')}}"
      cred_user: ''
      cred_pass: ''
      cred_filename: ''
      cred_filepath: ''
  register: text_secret_status
  changed_when: text_secret_status.output.find("credential") != -1
