- name: "waiting for Jenkins to come up"
  uri:
    url: "http://127.0.0.1:8080/cli"
    status_code: 200
    force_basic_auth: "{{ jenkins_secure }}"
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
