- hosts: all
  tasks:
    - name: disable firewall
      service:
        name: firewalld
        enabled: no
        state: stopped

- hosts: masters
  pre_tasks:
    - name: add jenkins repo
      yum_repository:
        baseurl: https://pkg.jenkins.io/redhat/
        gpgcheck: no
        description: jenkins repo
        name: jenkins
  roles:
    - { role: jenkins }

- hosts: nodes
  pre_tasks:
    - name: install the depednencies for the example
      yum:
        name:
          - gcc
          - make
          - openssl-devel
  roles:
    - { role: jenkins_node }
