- hosts: all
  tasks:
    - name: disable firewall
      service:
        name: firewalld
        enabled: no
        state: stopped

- hosts: masters
  pre_tasks:
    - name: add jenkins repo
      yum_repository:
        baseurl: https://pkg.jenkins.io/redhat/
        gpgcheck: no
        description: jenkins repo
        name: jenkins
  roles:
    - { role: jenkins }

- hosts: nodes
  pre_tasks:
    - name: add docker repo
      yum_repository:
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
        description: docker-ce repo
        name: docker-ce
    - name: install the depednencies for the example
      yum:
        name:
          - gcc
          - make
          - openssl-devel
  roles:
    - { role: docker }
    - { role: jenkins_node }
